### ISSUE TITLE
[LEARNING] Go Over React - Make Sure Everyone Can Work on React Platform

### ISSUE THREAD

**Issue by MaramRadhi** [MaramRadhi/ProjectPlanning#12]
**Task Description: **
Imran will go over the react application, he will go over the main parts, how to use the system, and help people understand the code sections. The main point of this meeting is help everyone be familiar and comfortable with the coding parts they will need to work on. 
**Task Action Description: **

**Comment by imrun10** [comment]
Manual Resources
https://www.w3schools.com/REACT/DEFAULT.ASP
https://expressjs.com/en/guide/routing.html 
https://expressjs.com/en/api.html 
https://www.w3schools.com/nodejs/nodejs_mysql.asp  
https://www.guru99.com/introduction-to-mysql-workbench.html
