### ISSUE TITLE
[INTERVIEW] First Interview with IT department (Maher) -  Gather Requirements

### ISSUE THREAD

**Issue by MaramRadhi** [MaramRadhi/ProjectPlanning#3]
**Task Description: ** 
Imran and Mariam need to work together to meet with the second user type "IT Department" representative Mr. Maher . Team members will have to first explain the system and his role in this project (since Dr.Haythm did not inform him about his role for this project). They will then need to conduct an interview with him asking about the main system requirement, and additional system feature IT department members might need. For example, creating new users, updating password, assigned account policies, any security and safety requirements needed for the system. 

**Task Action Description: **
 What are you looking for in the app
    - office 365 single sign on
    - user friendly - easier to edit data and upload files and save into database
    - difficult to fulfill staff requests for access
    - cloud based or local server
    - not outdated
    - not laggy
- What are your biggest concerns
    - everything can be done through web app

**Comment by imrun10** [comment]
Interview has been completed by Mariam
