### ISSUE TITLE
#33 [Developing- Server]  Admin Page

### ISSUE THREAD

**Issue by imrun10** [MaramRadhi/ProjectPlanning#33]
**Task Description: **
We will create an admin page for the it to use that allows them to add, edit delete any set of data for the users. we will also create a rest api to handle these requests

imran:  Work on the front end part learn about react-admin and try to get the front end part ready
huda: Create the rest api

**Comment by imrun10** [comment]
https://expressjs.com/en/starter/basic-routing.html

types of request

get 
post
put 
delete


GET
We need a get a request for:
Getting the courses
Getting the users
Getting the faculty and the courses they in
Getting the students and the courses they in 
No need to get grades and assignments and whatever

POST
Adding a student with all their required detail (only essentials like id fname last name)
Adding a user with all their required detail (username password)
Adding a course (name coursename)
Adding new faculty (fname lastname no need for courses)
No need to add grades that for the other users

PUT
Updating Faculty to have certain courses or to remov courses
Updating Students to have certain courses or to not be in certain courses
Updating user to have different permission levels

Delete
Delete for all different things except things to do with grades etc

**Comment by MaramRadhi** [comment]
**Note:**
Please refer to the image below, the system MUST be identical to the system features mentioned in the SRS document. 

IT Department Features - refer to feature 4.7, 4.8, and 4.9
![Image](https://user-images.githubusercontent.com/126344526/230503958-9fd90939-a156-4735-a208-d4454d5a88dc.png)

**Comment by imrun10** [comment]
Functionality of the admin a page will simple be editing every sing value in the database which will then update the front end view of the user

**Comment by imrun10** [comment]
Update: only one-quarter of the admin page has been made. the rest will be developed in the future. the rest api is completed and huda found a way to make it secure
