### ISSUE TITLE
#24 [Developing- Front End ] Course summary Page

### ISSUE THREAD

**Issue by imrun10** [MaramRadhi/ProjectPlanning#34]
**Task Description: **

1. create a course summary page similar to a student summary
2 . add a button to show go to course summary on the main page

**Comment by MaramRadhi** [comment]
**Note:**
Please refer to the image below, the system MUST be idebtical to the system features mentioned in the SRS document. 

Over All Course Summary 
![Image](https://user-images.githubusercontent.com/126344526/230503533-ebdc97c4-c3c8-4290-9b82-d6727f87bf49.png)

**Comment by imrun10** [comment]
Matthew has completed this however is experiencing major bugs that imran is currently fixing
