### ISSUE TITLE
#35 [Database] Simplifying the Database

### ISSUE THREAD

**Issue by imrun10** [MaramRadhi/ProjectPlanning#35]
**Task Description: **
reduce the amount o tables to just the ones we need. or collapse different tables into just one table

**Comment by Hudajpg** [comment]
Redesign the schema in order to reduce the amount of tables and relationships for it to match the test arrays used prior to the database connection. 
- Modify Courses table for the array to match the course summary page 
- Modify Students table for the array to match the student summary page
