### ISSUE TITLE
#36 [Developing] Student Course Summary

### ISSUE THREAD

**Issue by imrun10** [MaramRadhi/ProjectPlanning#36]
**Task Description: **
Make student summary get its data from the database not an array

**Comment by Hudajpg** [comment]
update the code for the student summary page to have a query that gets data from the database (student data and grades from database)

**Comment by MaramRadhi** [comment]
**Note:**
Please refer to the image below, the system MUST be idebtical to the system features mentioned in the SRS document. 

Student Summary 
![Image](https://user-images.githubusercontent.com/126344526/230503317-3a02f55e-7dff-44a7-9789-6c8255c22d11.png)

Over All Course Summary 
![Image](https://user-images.githubusercontent.com/126344526/230503533-ebdc97c4-c3c8-4290-9b82-d6727f87bf49.png)

**Comment by imrun10** [comment]
student summary page will be done by imran nasir
