### ISSUE TITLE
#38 [Developing] Download Summary

### ISSUE THREAD

**Issue by imrun10** [MaramRadhi/ProjectPlanning#38]
**Task Description: **
Turn the download summary button into a component and put it in both the student summary and course summary. in the component make it take a screenshot of the page and convert it to PDF.

https://pspdfkit.com/blog/2022/how-to-convert-html-to-pdf-using-react/

**Comment by MaramRadhi** [comment]
Note:
Please refer to the image below, the system MUST be identical to the system features mentioned in the SRS document.

Download Summary Feature 
![Image](https://user-images.githubusercontent.com/126344526/230504273-0d0d3f6d-9edc-4c82-9956-93e1bbd31438.png)
