### ISSUE TITLE
#45 [Developing] Improving UI

### ISSUE THREAD

**Issue by imrun10** [MaramRadhi/ProjectPlanning#45]
**Task Description:**
1) in the login page add the picture present in the figma file (can be found in github)-shahd
2) create a footer components to all pages. footer should contain just a link to aubh website and a link to canvas - farooq
3) take the trio buttons in the coursepages.js and copy paste them into a buttons component and just place that buttons component where you found it

**Comment by MaramRadhi** [comment]
Note non of the assigned worked on their part.
